CREATE DATABASE IF NOT EXISTS EmployeeDb
GO

CREATE TABLE IF NOT EXISTS Employee (
Id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
FirstName VARCHAR(100) NOT NULL,
LastName VARCHAR(100),
Age INT(3),
Gender VARCHAR(10) NOT NULL,
Salary DECIMAL(10,2) NOT NULL,
CreatedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)
GO